on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      OPEN_ZAAK_VERSION: 1.26.0
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out open-zaak ${{ env.OPEN_ZAAK_VERSION }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: maykinmedia/open-zaak
          ref: ${{ env.OPEN_ZAAK_VERSION }}

      - name: Build open-zaak Docker image for ARM64
        run: docker build --platform arm64 --tag ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }} .

      - name: Push open-zaak Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/open-zaak:${{ env.OPEN_ZAAK_VERSION }}
